#ifndef CONSTANTS_H
#define CONSTANTS_H

#define PRINT_DELAY_MS 35
#define PRINT_DELAY_NEWLINE_MULTIPLIER 10

#define MAX_DIALOGUE_STEPS 1024
#define MAX_DIALOGUE_LENGTH 4096
#define MAX_LABEL_LENGTH 32

#define BREAK_CHARACTER ')'
#define JUMP_CHARACTER '('
#define CHOICE_CHARACTER '|'
#define END_KEYWORD "end"

#define COUNTER_TOKEN ".- "
#define PROMPT_TOKEN "---> "

#endif

